version: "3.2"
services:
  server:
    build: ./server
    ports:
    - "80:5000"
    volumes:
    - ./server:/app
    environment:
        - FLASK_ENV:developement
  web:
    build: ./client
    ports:
    - "3000:3000"
    volumes:
    - ./client:/user/src/app
    depends_on:
    - server
